# Generated by Django 4.0.5 on 2022-07-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
